# Generated by Django 4.2.7 on 2025-11-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        help_text="Stripe Payment Intent ID",
                        max_length=255,
                        unique=True,
                        verbose_name="stripe payment intent ID",
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Checkout Session ID",
                        max_length=255,
                        verbose_name="stripe checkout session ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Payment currency code",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method used",
                        max_length=50,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to payment receipt",
                        verbose_name="receipt URL",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if payment failed",
                        verbose_name="error message",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Order associated with this payment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="payment_pay_stripe__46a826_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="payment_pay_order_i_b37863_idx",
                    ),
                ],
            },
        ),
    ]
