# Generated by Django 4.2.7 on 2025-11-02 16:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_remove_product_stock_quantity_alter_product_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="Unique order identifier",
                        max_length=50,
                        unique=True,
                        verbose_name="order number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current order status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "shipping_first_name",
                    models.CharField(
                        help_text="Shipping first name",
                        max_length=150,
                        verbose_name="first name",
                    ),
                ),
                (
                    "shipping_last_name",
                    models.CharField(
                        help_text="Shipping last name",
                        max_length=150,
                        verbose_name="last name",
                    ),
                ),
                (
                    "shipping_email",
                    models.EmailField(
                        help_text="Shipping email address",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "shipping_phone",
                    models.CharField(
                        help_text="Shipping phone number",
                        max_length=20,
                        verbose_name="phone",
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        help_text="Street address",
                        max_length=255,
                        verbose_name="address",
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(
                        help_text="City", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "shipping_state",
                    models.CharField(
                        help_text="State/Province", max_length=100, verbose_name="state"
                    ),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(
                        help_text="Postal/ZIP code",
                        max_length=20,
                        verbose_name="postal code",
                    ),
                ),
                (
                    "shipping_country",
                    models.CharField(
                        help_text="Country", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Order subtotal",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Shipping cost",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="shipping cost",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Order total",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Order notes from customer",
                        verbose_name="notes",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="Shipping tracking number",
                        max_length=100,
                        verbose_name="tracking number",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who placed the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity ordered",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit at time of order",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="price",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product ordered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product variant ordered",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "product"],
                        name="orders_orde_order_i_52f79a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="orders_orde_user_id_02a211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="orders_orde_created_0e92de_idx"
            ),
        ),
    ]
