# Generated by Django 4.2.7 on 2025-11-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock_quantity",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Product base price",
                max_digits=10,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price adjustment for this variant (can be negative)",
                max_digits=10,
                verbose_name="price adjustment",
            ),
        ),
    ]
